#!/usr/bin/env bash

source ~/.ec1/00mu/bbpager/00livelinks/launch_command/bbpager_launch
source ~/.ec1/00mu/00idcom/os_wallpaper_command
source ~/.ec1/00mu/conky/00configs/conky_rcs
source ~/.ec1/00mu/bash/00livelinks/su_terminal_launch/su_terminal_launch

# vim: ft=sh
