#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/c1pprod/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

#source ~/.ec1/00mu/00sourcing/ec1_livelinks/bash/4.x/configs/ub11.04/x86_64/.profile/ext_standard_01/.profile.ec1ext
#source ~/.ec1/00mu/bash/00livelinks/startup_virtual/startup_virtual

#source ~/.ec1/00mu/00sourcing/ec1_livelinks/bash/4.x/configs/ub11.04/x86_64/variable_export_term/rxvt_01/variable_export_term
#source ~/.ec1/00mu/00sourcing/ec1_livelinks/bash/4.x/configs/ub11.04/x86_64/variable_export_path_ec1_00loading/standard_01/variable_export_path_ec1_00loading
#source ~/.ec1/00mu/00sourcing/ec1_livelinks/bash/4.x/configs/ub11.04/x86_64/variable_export_rubylib_ec1_00loading/standard_01/variable_export_rubylib_ec1_00loading

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
#exec ssh-agent fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/c1pprod/.fluxbox/log"
